language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.sbt -name "*.lock" | xargs rm
