language: scala
sudo: false
services:
  - docker
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.sbt -name "*.lock" | xargs rm
deploy:
  provider: script
  script: bash script/docker-push
  on:
    branch: develop
