version: 2
jobs:
  build:
    working_directory: ~/api
    docker:
      - image: kavinvin/scala-sbt:2.12.5-1.1.2
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: cat /dev/null | sbt test:compile
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - run: cat /dev/null | sbt test:test
